name: art_wave
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  email_validator: ^2.1.17
  cloud_firestore: ^4.8.0
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.4
  lottie: ^2.4.0
  image_picker: ^0.8.9
  image_picker_web: ^3.0.0+1
  firebase_storage: ^11.2.3
  firebase_storage_web: ^3.6.3
  file_picker: ^5.3.2
  open_file: ^3.3.2
  universal_html: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
